[package]
name = "Threads"
version = "0.1.0"
authors = ["Jordi Pujol Ricarte <jpricarte@inf.ufrgs.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
spmc = "0.3.0"